package: cronmon
user: malev

platform:
  - linux-64
  - osx-64

engine:
  - python=2.7

install:
  - conda build conda.recipe
  - conda install cronmon --use-local

test:
  - cronmon --help
  - cronmon run -c ls -n ls -l ./

script:
  - conda build --no-test ./conda.recipe/

build_targets: conda
