package:
  name: cronmon
  version: "0.2.0"

build:
  script: python setup.py install

requirements:
  build:
    - click
    - flask
    - jinja2
    - python
  run:
    - click
    - flask
    - jinja2
    - python

source:
  path: ../

about:
  home: https://github.com/malev/cronmon
