{% set data = load_setuptools()%}
package:
  name: cronmon
  version: {{data.get('version')}}

build:
  script: python setup.py install

requirements:
  build:
    - click
    - flask
    - jinja2
    - python
  run:
    - click
    - flask
    - jinja2
    - python

source:
  path: ../

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
