{% set data = load_setuptools()%}
package:
  name: cronmon
  version: {{data.get('version')}}

build:
  script:
    - cd $RECIPE_DIR/..
    - $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - click
    - flask
    - jinja2
    - python
    - pyyaml
  run:
    - click
    - flask
    - jinja2
    - python
    - pyyaml

source:
  path: ../

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
